version: "2.1"

services:
  foldingathome:
    image: linuxserver/foldingathome
    container_name: foldingathome
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./folding:/config
    ports:
      - 8084:7396
      # - 36330:36330 #optional
    networks:
      - ian
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`folding.ianmyjer.com`)" 
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.routers.ghost.tls.certresolver=myhttpchallenge"

networks:
  ian:
    external: true