version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./letsencrypt/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.ianmyjer.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.auth.basicauth.users=ian:$$apr1$$pedizur5$$tfpDsNxWXlZ2MBR2X4p5d/"

  flaskian:
    container_name: flaskian
    build:
      context: ../../flaskian/
      dockerfile: Dockerfile
    image: ian
    restart: unless-stopped
    ports: 
      - "8081:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ian-sec.rule=Host(`ianmyjer.com`, `www.ianmyjer.com`)" 
      - "traefik.http.routers.ian-sec.entrypoints=websecure"
      - "traefik.http.routers.ian-sec.tls=true"
      - "traefik.http.routers.ian-sec.tls.certresolver=myhttpchallenge"
      # - "traefik.http.routers.ian-norm.rule=Host(`ianmyjer.com`, `www.ianmyjer.com`)"
      # - "traefik.http.routers.ian-norm.entrypoints=web"
