log:
  filePath: "./traefik.log"
  level: "DEBUG"

metrics: {}
tracing: {}


entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

api:
  insecure: true
  dashboard: true


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false


certificatesResolvers:
  myhttpchallenge:
    acme:
      email: "ian@ianmyjer.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

