entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ':443'

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: "ian@ianmyjer.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

